### PR TITLE
hiera.yaml updated to use OS and major release

### PR DESCRIPTION
**Pull request by parryb**
I have updated hiera.yaml to use the OS name and renamed the hiera data files in data/cis to reflect what facter returns.  I don't know all of the exact names for every Linux you support but have completed RedHat, AlmaLinux, CentOS and Ubuntu.

### CODE REVIEW

**Comment by parryb** [comment]
Argh! Git has recorded my file name changes for the hiera data.

**Review by tom-krieger — CHANGES_REQUESTED** [review]
This won't work because the hiera data files are all lower case. For AlmaLinux the _os.name_ is "AlmaLinux", the filename currently is "cis_almalinux_8_params.yaml". Same for the rules file. Either the data files have to be changed or the fact has to be converted to all lowercase. I don't want to rely on upper/lower case writings of os names at the moment. So my preferred solution is tpo convert the _os.name_ fact to lowercase.

**Comment by parryb** [comment]
Agreed, lower case would be better.  I had the same thoughts when writing the fix, although I don't think it's possible to downcase facts in hiera.

**Comment by parryb** [comment]
> Btw. can you please tell me what the problems have been with the default config of the module and not compiling? I would like to have a look at that to fix these things.

There is a duplicate declaration of firewalld service (firewalld_service.pp) between your module and the puppetlabs firewall (redhat.pp) also one with Package[iptables-services] and the same Puppetlabs/firewall (redhat.pp).

It can be worked around by disabling the cis_security_hardening functionality.

**Comment by tom-krieger** [comment]
Included in release 0.7.7, so I close this one.

**Pull request closed without merging**
