### PR TITLE
Removed class name from variable declaration (issue #36)

### PR DESCRIPTION
**Pull request by parryb**
Here is promised pull request to fix issue 36

### CODE REVIEW

**Review by tom-krieger — COMMENTED** [review]
Removing Cis_security_hardening::Nftables_address_families removes security. This type is to make sure that no malicious code can be inserted into the nftables command. I won't accept this pull request.

**Comment by parryb** [comment]
> Removing Cis_security_hardening::Nftables_address_families removes security. This type is to make sure that no malicious code can be inserted into the nftables command. I won't accept this pull request.

Hhhhmmmm, OK.  I couldn't get the module to work with that class name in the variable definition.  I've never seen or used class names in the variable definition before.

**Comment by parryb** [comment]
I don't suppose you could point me to the documentation about that usage?  Because puppet.com doesn't seem to have anything.

**Comment by parryb** [comment]
Fixed the error we were seeing which was caused by old hiera data.  Had a look at your type (nftables_address_families.pp) code I get what is going on, I just can't find any documentation on using it in class parameter definition.

**Pull request closed without merging**
